services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch-plugins.yml:/usr/share/elasticsearch/config/elasticsearch-plugins.yml

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS -X POST 'http://localhost:9200/_analyze' -H 'Content-Type: application/json' -d '{\"analyzer\":\"smartcn\",\"text\":\"中华人民共和国\"}' | grep -q 'tokens'"
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.4
    container_name: kibana
    restart: unless-stopped

    depends_on:
      elasticsearch:
        condition: service_healthy

    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

    ports:
      - "5601:5601"
    networks:
      - elastic

volumes:
  es_data:

networks:
  elastic:

