#启动命令 docker compose -f docker-compose-mid.yml up -d
services:
  code-forge-mysql:
    container_name: code-forge-mysql
    image: mysql:8.4.2
    ports:
      - "3306:3306"
    volumes:
      - ../data/codeforgedata/mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1',
      '--explicit_defaults_for_timestamp=true',
      '--server-id=1',
      '--log-bin=mysql-bin',
      '--binlog-ignore-db=mysql',
      '--binlog-cache-size=256M',
      '--binlog-format=ROW',
      '--max_connections=2000'
    ]
    restart: always
    networks:
      - codeforge_network
    healthcheck:
      test: mysql --user=wjl -h127.0.0.1 --password='wjl@123' -e "SELECT 1;"
      start_period: 180s
      interval: 5s
      timeout: 5s
      retries: 12
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: wjl@123
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  code-forge-nacos:
    container_name: code-forge-nacos
    image: nacos/nacos-server:v2.2.2
    environment:
      - MODE=standalone
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=code-forge-mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=frameworkjava_nacos_test
      - MYSQL_SERVICE_USER=wjl
      - MYSQL_SERVICE_PASSWORD=wjl@123
    volumes:
      - ../data/codeforgedata/nacos/logs/:/home/nacos/logs
      - ../data/codeforgedata/nacos/tomcatlogs/:/home/bit/nacos/tomcat/logs/
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    restart: always
    networks:
      - codeforge_network
    depends_on:
      code-forge-mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos" ]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10

  code-forge-redis:
    container_name: code-forge-redis
    image: redis:7.0.15
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ../data/codeforgedata/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - codeforge_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  codeforge_network:
