SET NAMES utf8mb4;
USE `db_code_forge`;

-- 题目 1：两数之和
INSERT INTO tb_question
(title, difficulty, time_limit, space_limit, content, question_case, default_code, main_fuc, create_by, create_time)
VALUES
    ('两数之和', 1, 1000, 65536,
     '题目描述：\n给定两个整数 a 和 b，输出它们的和。\n\n示例 1：\n输入：1 2\n输出：3\n\n示例 2：\n输入：-5 7\n输出：2\n\n提示：\n- a、b 均为 int 范围内的整数。',
     '1 2|||3\n-5 7|||2\n0 0|||0',
     'class Solution {\n    public int add(int a, int b) {\n        // TODO: 在这里编写你的代码\n    }\n}',
     'import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.add(a, b));\n    }\n}\n{{USER_CODE}}',
     1, now()),
    ('两数之差', 1, 1000, 65536,
     '题目描述：\n给定两个整数 a 和 b，输出 a - b 的结果。\n\n示例 1：\n输入：5 3\n输出：2\n\n示例 2：\n输入：0 10\n输出：-10\n\n提示：\n- 结果可能为负数。',
     '5 3|||2\n0 10|||-10\n100 100|||0',
     'class Solution {\n    public int subtract(int a, int b) {\n        // TODO: 在这里编写你的代码\n    }\n}',
     'import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.subtract(a, b));\n    }\n}\n{{USER_CODE}}',
     1, now()),
    ('判断奇偶', 1, 1000, 65536,
     '题目描述：\n给定一个整数 n，如果 n 是偶数输出 even，否则输出 odd。\n\n示例 1：\n输入：4\n输出：even\n\n示例 2：\n输入：7\n输出：odd\n\n提示：\n- n 为 int 范围内的整数。',
     '4|||even\n7|||odd\n0|||even',
     'class Solution {\n    public String check(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}',
     'import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.check(n));\n    }\n}\n{{USER_CODE}}',
     1, now()),
    ('三个数中的最大值', 1, 1000, 65536,
     '题目描述：\n给定三个整数 a、b、c，输出其中的最大值。\n\n示例 1：\n输入：1 2 3\n输出：3\n\n示例 2：\n输入：-1 -5 -3\n输出：-1\n\n提示：\n- 三个数均为 int 范围内的整数。',
     '1 2 3|||3\n-1 -5 -3|||-1\n0 0 0|||0',
     'class Solution {\n    public int maxOfThree(int a, int b, int c) {\n        // TODO: 在这里编写你的代码\n    }\n}',
     'import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        int c = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.maxOfThree(a, b, c));\n    }\n}\n{{USER_CODE}}',
     1, now()),
    ('阶乘', 2, 1000, 65536,
     '题目描述：\n给定一个非负整数 n，输出 n! 的值。\n\n示例 1：\n输入：5\n输出：120\n\n示例 2：\n输入：0\n输出：1\n\n提示：\n- 0 ≤ n ≤ 12，结果在 int 范围内。',
     '5|||120\n0|||1\n1|||1',
     'class Solution {\n    public int factorial(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}',
     'import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.factorial(n));\n    }\n}\n{{USER_CODE}}',
     1, now()),
    ('斐波那契数列', 2, 1000, 65536,
     '题目描述：\n斐波那契数列定义为 F(0)=0，F(1)=1，F(n)=F(n-1)+F(n-2)。给定 n，输出 F(n)。\n\n示例 1：\n输入：10\n输出：55\n\n示例 2：\n输入：0\n输出：0\n\n提示：\n- 0 ≤ n ≤ 30。',
     '10|||55\n0|||0\n1|||1',
     'class Solution {\n    public int fib(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}',
     'import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.fib(n));\n    }\n}\n{{USER_CODE}}',
     1, now()),
    ('数组求和', 2, 1000, 65536,
     '题目描述：\n第一行输入整数 n，第二行输入 n 个整数，输出它们的和。\n\n示例 1：\n输入：5\n1 2 3 4 5\n输出：15\n\n示例 2：\n输入：3\n-1 0 1\n输出：0\n\n提示：\n- 1 ≤ n ≤ 1000。',
     '5\n1 2 3 4 5|||15\n3\n-1 0 1|||0\n1\n100|||100',
     'class Solution {\n    public int sum(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}',
     'import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.sum(arr));\n    }\n}\n{{USER_CODE}}',
     1, now()),
    ('字符串反转', 2, 1000, 65536,
     '题目描述：\n给定一个字符串 s，输出它的反转字符串。\n\n示例 1：\n输入：hello\n输出：olleh\n\n示例 2：\n输入：abc\n输出：cba\n\n提示：\n- s 仅包含小写字母，长度不超过 1000。',
     'hello|||olleh\nabc|||cba\na|||a',
     'class Solution {\n    public String reverse(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}',
     'import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.reverse(s));\n    }\n}\n{{USER_CODE}}',
     1, now()),
    ('判断素数', 3, 1000, 65536,
     '题目描述：\n给定一个正整数 n，如果 n 是素数输出 yes，否则输出 no。\n\n示例 1：\n输入：7\n输出：yes\n\n示例 2：\n输入：1\n输出：no\n\n提示：\n- 1 ≤ n ≤ 100000。\n- 1 不是素数。',
     '7|||yes\n1|||no\n4|||no\n2|||yes',
     'class Solution {\n    public String isPrime(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}',
     'import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.isPrime(n));\n    }\n}\n{{USER_CODE}}',
     1, now());

INSERT INTO tb_question
(title, difficulty, time_limit, space_limit, content, question_case, default_code, main_fuc, create_by, create_time)
VALUES
    ('最大公约数', 3, 1000, 65536,
     '题目描述：\n给定两个正整数 a 和 b，输出它们的最大公约数。\n\n示例 1：\n输入：12 18\n输出：6\n\n示例 2：\n输入：7 13\n输出：1\n\n提示：\n- 1 ≤ a, b ≤ 100000。',
     '12 18|||6\n7 13|||1\n100 75|||25',
     'class Solution {\n    public int gcd(int a, int b) {\n        // TODO: 在这里编写你的代码\n    }\n}',
     'import java.util.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.gcd(a, b));\n    }\n}\n{{USER_CODE}}',
     1, now());

INSERT INTO tb_question
(title, difficulty, time_limit, space_limit, content, question_case, default_code, main_fuc, create_by, create_time, update_by, update_time)
VALUES
    ('数字反转', 2, 1000, 65536, '题目描述：\n给定一个整数 n，输出它的数字反转结果。\n\n示例 1：\n输入：123\n输出：321\n\n示例 2：\n输入：-456\n输出：-654\n\n提示：\n- n 为 int 范围内的整数。', '123|||321\n-456|||-654\n0|||0', 'class Solution {\n    public int reverseInt(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.reverseInt(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('回文数判断', 2, 1000, 65536, '题目描述：\n给定一个整数 n，判断它是否为回文数。是输出 yes，否则输出 no。\n\n示例 1：\n输入：121\n输出：yes\n\n示例 2：\n输入：-121\n输出：no\n\n提示：\n- 负数不是回文数。', '121|||yes\n-121|||no\n0|||yes', 'class Solution {\n    public String isPalindrome(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.isPalindrome(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组最大值', 1, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，输出最大值。\n\n示例 1：\n输入：5\n1 2 3 4 5\n输出：5\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n1 2 3 4 5|||5\n3\n-1 -2 -3|||-1', 'class Solution {\n    public int max(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.max(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组最小值', 1, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，输出最小值。\n\n示例 1：\n输入：5\n3 1 4 1 5\n输出：1\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n3 1 4 1 5|||1\n3\n-1 -2 -3|||-3', 'class Solution {\n    public int min(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.min(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组平均值', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，输出它们的平均值（保留两位小数）。\n\n示例 1：\n输入：4\n1 2 3 4\n输出：2.50\n\n提示：\n- 使用 printf("%.2f") 输出。', '4\n1 2 3 4|||2.50\n2\n-1 1|||0.00', 'class Solution {\n    public double average(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.printf("%.2f%n", s.average(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('统计正数个数', 1, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，统计其中正数的个数。\n\n示例 1：\n输入：5\n-1 2 -3 4 5\n输出：3\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n-1 2 -3 4 5|||3\n3\n-1 -2 -3|||0', 'class Solution {\n    public int countPositive(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.countPositive(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串长度', 1, 1000, 65536, '题目描述：\n给定一个字符串 s，输出它的长度。\n\n示例 1：\n输入：hello\n输出：5\n\n提示：\n- s 长度不超过 1000。', 'hello|||5\nabc|||3', 'class Solution {\n    public int length(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.length(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串转大写', 1, 1000, 65536, '题目描述：\n给定一个字符串 s（仅小写字母），输出它的大写形式。\n\n示例 1：\n输入：hello\n输出：HELLO\n\n提示：\n- 使用 toUpperCase()。', 'hello|||HELLO\nworld|||WORLD', 'class Solution {\n    public String toUpper(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.toUpper(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串转小写', 1, 1000, 65536, '题目描述：\n给定一个字符串 s（仅大写字母），输出它的小写形式。\n\n示例 1：\n输入：HELLO\n输出：hello\n\n提示：\n- 使用 toLowerCase()。', 'HELLO|||hello\nWORLD|||world', 'class Solution {\n    public String toLower(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.toLower(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串拼接', 2, 1000, 65536, '题目描述：\n给定两个字符串 a 和 b，输出 a + b 的结果。\n\n示例 1：\n输入：hello world\n输出：helloworld\n\n提示：\n- 使用 + 拼接。', 'hello world|||helloworld\nabc def|||abcdef', 'class Solution {\n    public String concat(String a, String b) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String a = sc.next();\n        String b = sc.next();\n        Solution s = new Solution();\n        System.out.println(s.concat(a, b));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符出现次数', 2, 1000, 65536, '题目描述：\n给定字符串 s 和一个字符 c，统计 c 在 s 中出现的次数。\n\n示例 1：\n输入：hello l\n输出：2\n\n提示：\n- 遍历字符串比较。', 'hello l|||2\nabc a|||1', 'class Solution {\n    public int countChar(String s, char c) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        char c = sc.next().charAt(0);\n        Solution solution = new Solution();\n        System.out.println(solution.countChar(s, c));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('判断闰年', 2, 1000, 65536, '题目描述：\n给定一个年份 y，判断是否为闰年。是输出 yes，否则输出 no。\n\n示例 1：\n输入：2020\n输出：yes\n\n提示：\n- 能被4整除且不能被100整除，或能被400整除。', '2020|||yes\n1900|||no\n2000|||yes', 'class Solution {\n    public String isLeap(int y) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int y = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.isLeap(y));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('判断水仙花数', 2, 1000, 65536, '题目描述：\n给定一个三位数 n，判断是否为水仙花数（各位立方和等于本身）。是输出 yes，否则输出 no。\n\n示例 1：\n输入：153\n输出：yes\n\n提示：\n- 1^3 + 5^3 + 3^3 = 153。', '153|||yes\n370|||yes\n100|||no', 'class Solution {\n    public String isNarcissistic(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.isNarcissistic(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('求和 1 到 n', 1, 1000, 65536, '题目描述：\n给定正整数 n，输出 1 + 2 + ... + n 的结果。\n\n示例 1：\n输入：10\n输出：55\n\n提示：\n- 1 ≤ n ≤ 10000。', '10|||55\n1|||1\n100|||5050', 'class Solution {\n    public int sumToN(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.sumToN(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('阶乘和', 3, 1000, 65536, '题目描述：\n给定正整数 n，输出 1! + 2! + ... + n! 的结果。\n\n示例 1：\n输入：3\n输出：9\n\n提示：\n- 1 ≤ n ≤ 12。', '3|||9\n1|||1\n4|||33', 'class Solution {\n    public int factorialSum(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.factorialSum(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数字位数', 1, 1000, 65536, '题目描述：\n给定一个正整数 n，输出它的位数。\n\n示例 1：\n输入：12345\n输出：5\n\n提示：\n- 1 ≤ n ≤ 10^9。', '12345|||5\n7|||1\n100|||3', 'class Solution {\n    public int digits(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.digits(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数字各位和', 2, 1000, 65536, '题目描述：\n给定一个正整数 n，输出它各位数字之和。\n\n示例 1：\n输入：123\n输出：6\n\n提示：\n- 1 ≤ n ≤ 10^9。', '123|||6\n999|||27\n10|||1', 'class Solution {\n    public int digitSum(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.digitSum(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('交换两个数', 1, 1000, 65536, '题目描述：\n输入两个整数 a 和 b，输出交换后的值，以空格分隔。\n\n示例 1：\n输入：1 2\n输出：2 1\n\n提示：\n- 使用临时变量交换。', '1 2|||2 1\n-5 10|||10 -5', 'class Solution {\n    public int[] swap(int a, int b) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.swap(a, b);\n        System.out.println(res[0] + " " + res[1]);\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('判断正负零', 1, 1000, 65536, '题目描述：\n给定一个整数 n，输出 positive、negative 或 zero。\n\n示例 1：\n输入：5\n输出：positive\n\n提示：\n- n 为 int 范围内的整数。', '5|||positive\n-3|||negative\n0|||zero', 'class Solution {\n    public String sign(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.sign(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('绝对值', 1, 1000, 65536, '题目描述：\n给定一个整数 n，输出它的绝对值。\n\n示例 1：\n输入：-5\n输出：5\n\n提示：\n- 使用 Math.abs()。', '-5|||5\n3|||3\n0|||0', 'class Solution {\n    public int abs(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.abs(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL);

INSERT INTO tb_question
(title, difficulty, time_limit, space_limit, content, question_case, default_code, main_fuc, create_by, create_time, update_by, update_time)
VALUES
    ('求平方', 1, 1000, 65536, '题目描述：\n给定一个整数 n，输出 n 的平方。\n\n示例 1：\n输入：5\n输出：25\n\n提示：\n- 结果在 long 范围内。', '5|||25\n-3|||9\n0|||0', 'class Solution {\n    public long square(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.square(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('求立方', 1, 1000, 65536, '题目描述：\n给定一个整数 n，输出 n 的立方。\n\n示例 1：\n输入：3\n输出：27\n\n提示：\n- 结果在 long 范围内。', '3|||27\n-2|||-8\n0|||0', 'class Solution {\n    public long cube(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.cube(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('两数之积', 1, 1000, 65536, '题目描述：\n给定两个整数 a 和 b，输出它们的乘积。\n\n示例 1：\n输入：3 4\n输出：12\n\n提示：\n- 使用 long 防止溢出。', '3 4|||12\n-5 6|||-30\n0 100|||0', 'class Solution {\n    public long multiply(int a, int b) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.multiply(a, b));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('两数之商', 2, 1000, 65536, '题目描述：\n给定两个整数 a 和 b，输出 a / b 的整数部分。\n\n示例 1：\n输入：10 3\n输出：3\n\n提示：\n- 保证 b 不为 0。', '10 3|||3\n-10 3|||-3\n7 7|||1', 'class Solution {\n    public int divide(int a, int b) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.divide(a, b));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('两数之余', 2, 1000, 65536, '题目描述：\n给定两个整数 a 和 b，输出 a % b 的结果。\n\n示例 1：\n输入：10 3\n输出：1\n\n提示：\n- 保证 b 不为 0。', '10 3|||1\n-10 3|||-1\n7 7|||0', 'class Solution {\n    public int mod(int a, int b) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.mod(a, b));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('三数之和', 1, 1000, 65536, '题目描述：\n给定三个整数 a、b、c，输出它们的和。\n\n示例 1：\n输入：1 2 3\n输出：6\n\n提示：\n- 结果在 int 范围内。', '1 2 3|||6\n-1 -2 -3|||-6\n0 0 0|||0', 'class Solution {\n    public int sum3(int a, int b, int c) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        int c = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.sum3(a, b, c));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('三数之积', 1, 1000, 65536, '题目描述：\n给定三个整数 a、b、c，输出它们的乘积。\n\n示例 1：\n输入：1 2 3\n输出：6\n\n提示：\n- 使用 long 防止溢出。', '1 2 3|||6\n-1 2 3|||-6\n0 1 2|||0', 'class Solution {\n    public long product3(int a, int b, int c) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        int c = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.product3(a, b, c));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('三数最小值', 1, 1000, 65536, '题目描述：\n给定三个整数 a、b、c，输出其中的最小值。\n\n示例 1：\n输入：1 2 3\n输出：1\n\n提示：\n- 使用 Math.min()。', '1 2 3|||1\n-1 -5 -3|||-5\n0 0 0|||0', 'class Solution {\n    public int min3(int a, int b, int c) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        int c = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.min3(a, b, c));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('三数排序', 2, 1000, 65536, '题目描述：\n给定三个整数 a、b、c，从小到大输出，以空格分隔。\n\n示例 1：\n输入：3 1 2\n输出：1 2 3\n\n提示：\n- 可用数组排序。', '3 1 2|||1 2 3\n-1 5 0|||-1 0 5\n7 7 7|||7 7 7', 'class Solution {\n    public int[] sort3(int a, int b, int c) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        int c = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.sort3(a, b, c);\n        System.out.println(res[0] + " " + res[1] + " " + res[2]);\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('判断三角形', 2, 1000, 65536, '题目描述：\n给定三边 a、b、c，判断能否构成三角形。能输出 yes，否则输出 no。\n\n示例 1：\n输入：3 4 5\n输出：yes\n\n提示：\n- 任意两边之和大于第三边。', '3 4 5|||yes\n1 2 3|||no\n5 5 5|||yes', 'class Solution {\n    public String isTriangle(int a, int b, int c) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        int c = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.isTriangle(a, b, c));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('三角形面积', 3, 1000, 65536, '题目描述：\n给定三边 a、b、c，输出三角形面积（保留两位小数）。\n\n示例 1：\n输入：3 4 5\n输出：6.00\n\n提示：\n- 使用海伦公式，p = (a+b+c)/2。', '3 4 5|||6.00\n5 5 5|||10.83', 'class Solution {\n    public double area(int a, int b, int c) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        int c = sc.nextInt();\n        Solution s = new Solution();\n        System.out.printf("%.2f%n", s.area(a, b, c));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('成绩等级', 2, 1000, 65536, '题目描述：\n给定一个百分制成绩 s，输出等级：90-100 为 A，80-89 为 B，70-79 为 C，60-69 为 D，60 以下为 F。\n\n示例 1：\n输入：95\n输出：A\n\n提示：\n- 使用 if-else 判断。', '95|||A\n85|||B\n72|||C\n60|||D\n50|||F', 'class Solution {\n    public String grade(int s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int s = sc.nextInt();\n        Solution solution = new Solution();\n        System.out.println(solution.grade(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('判断元音', 1, 1000, 65536, '题目描述：\n给定一个小写字母 c，判断是否为元音（a/e/i/o/u）。是输出 yes，否则输出 no。\n\n示例 1：\n输入：a\n输出：yes\n\n提示：\n- 使用 switch 或 if 判断。', 'a|||yes\nb|||no\ne|||yes', 'class Solution {\n    public String isVowel(char c) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        char c = sc.next().charAt(0);\n        Solution s = new Solution();\n        System.out.println(s.isVowel(c));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('月份天数', 2, 1000, 65536, '题目描述：\n给定年份 y 和月份 m，输出该月天数。\n\n示例 1：\n输入：2020 2\n输出：29\n\n提示：\n- 闰年 2 月 29 天，平年 28 天。', '2020 2|||29\n1900 2|||28\n2021 4|||30', 'class Solution {\n    public int daysInMonth(int y, int m) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int y = sc.nextInt();\n        int m = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.daysInMonth(y, m));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('简单计算器', 3, 1000, 65536, '题目描述：\n给定两个整数 a、b 和一个运算符 op（+ - * /），输出运算结果（整数除法）。\n\n示例 1：\n输入：3 4 +\n输出：7\n\n提示：\n- 保证除数不为 0。', '3 4 +|||7\n10 3 -|||7\n6 2 *|||12\n10 3 /|||3', 'class Solution {\n    public int calc(int a, int b, char op) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt();\n        int b = sc.nextInt();\n        char op = sc.next().charAt(0);\n        Solution s = new Solution();\n        System.out.println(s.calc(a, b, op));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('统计偶数个数', 1, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，统计其中偶数的个数。\n\n示例 1：\n输入：5\n1 2 3 4 5\n输出：2\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n1 2 3 4 5|||2\n3\n1 3 5|||0\n4\n2 4 6 8|||4', 'class Solution {\n    public int countEven(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.countEven(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('统计负数个数', 1, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，统计其中负数的个数。\n\n示例 1：\n输入：5\n-1 2 -3 4 -5\n输出：3\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n-1 2 -3 4 -5|||3\n3\n1 2 3|||0\n2\n-1 -2|||2', 'class Solution {\n    public int countNegative(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.countNegative(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组倒序输出', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，将它们倒序输出，以空格分隔。\n\n示例 1：\n输入：5\n1 2 3 4 5\n输出：5 4 3 2 1\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n1 2 3 4 5|||5 4 3 2 1\n3\n-1 0 1|||1 0 -1', 'class Solution {\n    public int[] reverseArray(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.reverseArray(arr);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组元素查找', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，第三行输入目标值 x，输出 x 第一次出现的下标（从 0 开始），不存在输出 -1。\n\n示例 1：\n输入：5\n1 2 3 4 5\n3\n输出：2\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n1 2 3 4 5\n3|||2\n3\n1 2 3\n5|||-1', 'class Solution {\n    public int find(int[] arr, int x) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        int x = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.find(arr, x));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL);

INSERT INTO tb_question
(title, difficulty, time_limit, space_limit, content, question_case, default_code, main_fuc, create_by, create_time, update_by, update_time)
VALUES
    ('数组元素计数', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，第三行输入目标值 x，输出 x 出现的次数。\n\n示例 1：\n输入：5\n1 2 2 3 2\n2\n输出：3\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n1 2 2 3 2\n2|||3\n3\n1 2 3\n5|||0', 'class Solution {\n    public int count(int[] arr, int x) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        int x = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.count(arr, x));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组去重', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，输出去重后的数组（保持原顺序），以空格分隔。\n\n示例 1：\n输入：6\n1 2 2 3 1 4\n输出：1 2 3 4\n\n提示：\n- 1 ≤ n ≤ 1000。', '6\n1 2 2 3 1 4|||1 2 3 4\n3\n5 5 5|||5', 'class Solution {\n    public int[] unique(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.unique(arr);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组排序（升序）', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，将它们升序排序后输出，以空格分隔。\n\n示例 1：\n输入：5\n3 1 4 1 5\n输出：1 1 3 4 5\n\n提示：\n- 可使用 Arrays.sort()。', '5\n3 1 4 1 5|||1 1 3 4 5\n3\n-1 0 1|||-1 0 1', 'class Solution {\n    public int[] sortAsc(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.sortAsc(arr);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组排序（降序）', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，将它们降序排序后输出，以空格分隔。\n\n示例 1：\n输入：5\n3 1 4 1 5\n输出：5 4 3 1 1\n\n提示：\n- 可先升序再反转。', '5\n3 1 4 1 5|||5 4 3 1 1\n3\n-1 0 1|||1 0 -1', 'class Solution {\n    public int[] sortDesc(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.sortDesc(arr);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组第二大值', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，输出第二大的值（去重后）。若不存在输出 -1。\n\n示例 1：\n输入：5\n3 1 4 1 5\n输出：4\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n3 1 4 1 5|||4\n3\n5 5 5|||-1\n4\n1 2 3 4|||3', 'class Solution {\n    public int secondMax(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.secondMax(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组元素之和（偶数）', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，输出其中所有偶数的和。\n\n示例 1：\n输入：5\n1 2 3 4 5\n输出：6\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n1 2 3 4 5|||6\n3\n1 3 5|||0\n4\n2 4 6 8|||20', 'class Solution {\n    public int sumEven(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.sumEven(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组元素之和（奇数）', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，输出其中所有奇数的和。\n\n示例 1：\n输入：5\n1 2 3 4 5\n输出：9\n\n提示：\n- 1 ≤ n ≤ 1000。', '5\n1 2 3 4 5|||9\n3\n2 4 6|||0\n4\n1 3 5 7|||16', 'class Solution {\n    public int sumOdd(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.sumOdd(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组相邻元素之差', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，输出相邻元素之差的绝对值之和。\n\n示例 1：\n输入：4\n1 3 6 10\n输出：9\n\n提示：\n- |3-1| + |6-3| + |10-6| = 2+3+4 = 9。', '4\n1 3 6 10|||9\n3\n1 1 1|||0', 'class Solution {\n    public int adjacentDiff(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.adjacentDiff(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组是否升序', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，判断数组是否严格升序。是输出 yes，否则输出 no。\n\n示例 1：\n输入：4\n1 2 3 4\n输出：yes\n\n提示：\n- 严格升序指后一个数大于前一个数。', '4\n1 2 3 4|||yes\n3\n1 1 2|||no\n3\n3 2 1|||no', 'class Solution {\n    public String isSortedAsc(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.isSortedAsc(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组是否包含重复', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，判断数组是否有重复元素。有输出 yes，否则输出 no。\n\n示例 1：\n输入：4\n1 2 3 2\n输出：yes\n\n提示：\n- 可用 HashSet。', '4\n1 2 3 2|||yes\n3\n1 2 3|||no\n1\n5|||no', 'class Solution {\n    public String hasDuplicate(int[] arr) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.hasDuplicate(arr));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组交集', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数（数组 a），第三行输入 m，第四行输入 m 个整数（数组 b），输出两个数组的交集（去重、升序），以空格分隔。\n\n示例 1：\n输入：3\n1 2 3\n3\n2 3 4\n输出：2 3\n\n提示：\n- 使用 Set 处理。', '3\n1 2 3\n3\n2 3 4|||2 3\n2\n1 2\n2\n3 4|||', 'class Solution {\n    public int[] intersect(int[] a, int[] b) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n];\n        for (int i = 0; i < n; i++) a[i] = sc.nextInt();\n        int m = sc.nextInt();\n        int[] b = new int[m];\n        for (int i = 0; i < m; i++) b[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.intersect(a, b);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('数组并集', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数（数组 a），第三行输入 m，第四行输入 m 个整数（数组 b），输出两个数组的并集（去重、升序），以空格分隔。\n\n示例 1：\n输入：3\n1 2 3\n3\n2 3 4\n输出：1 2 3 4\n\n提示：\n- 使用 TreeSet。', '3\n1 2 3\n3\n2 3 4|||1 2 3 4\n2\n1 2\n2\n3 4|||1 2 3 4', 'class Solution {\n    public int[] union(int[] a, int[] b) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n];\n        for (int i = 0; i < n; i++) a[i] = sc.nextInt();\n        int m = sc.nextInt();\n        int[] b = new int[m];\n        for (int i = 0; i < m; i++) b[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.union(a, b);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串是否回文', 2, 1000, 65536, '题目描述：\n给定一个字符串 s（仅小写字母），判断它是否为回文串。是输出 yes，否则输出 no。\n\n示例 1：\n输入：level\n输出：yes\n\n提示：\n- 回文串正读反读相同。', 'level|||yes\nhello|||no\na|||yes', 'class Solution {\n    public String isPalindromeStr(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.isPalindromeStr(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('统计单词个数', 3, 1000, 65536, '题目描述：\n给定一行字符串（单词之间以空格分隔），输出单词个数。\n\n示例 1：\n输入：hello world java\n输出：3\n\n提示：\n- 使用 split 或 Scanner 读取。', 'hello world java|||3\nabc|||1\na b c d|||4', 'class Solution {\n    public int countWords(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.nextLine();\n        Solution solution = new Solution();\n        System.out.println(solution.countWords(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串首字母大写', 2, 1000, 65536, '题目描述：\n给定一个字符串 s（仅小写字母），将首字母大写后输出。\n\n示例 1：\n输入：hello\n输出：Hello\n\n提示：\n- 使用 substring 和 toUpperCase。', 'hello|||Hello\nworld|||World\na|||A', 'class Solution {\n    public String capitalize(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.capitalize(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('去除字符串空格', 1, 1000, 65536, '题目描述：\n给定一个字符串 s（可能含空格），输出去除所有空格后的字符串。\n\n示例 1：\n输入：h e l l o\n输出：hello\n\n提示：\n- 使用 replace 或遍历。', 'h e l l o|||hello\nabc|||abc\na b c|||abc', 'class Solution {\n    public String removeSpaces(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.nextLine();\n        Solution solution = new Solution();\n        System.out.println(solution.removeSpaces(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串压缩', 3, 1000, 65536, '题目描述：\n给定一个字符串 s（仅小写字母），按连续字符计数压缩。若压缩后长度不小于原串，输出原串。\n\n示例 1：\n输入：aaabbc\n输出：a3b2c1\n\n提示：\n- 1 ≤ |s| ≤ 1000。', 'aaabbc|||a3b2c1\nabc|||abc\naaaa|||a4', 'class Solution {\n    public String compress(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.compress(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串最长单词', 3, 1000, 65536, '题目描述：\n给定一行字符串（单词以空格分隔），输出最长的单词。若有多个，输出第一个。\n\n示例 1：\n输入：hello world java\n输出：hello\n\n提示：\n- 使用 split。', 'hello world java|||hello\na bb ccc|||ccc\nx y z|||x', 'class Solution {\n    public String longestWord(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.nextLine();\n        Solution solution = new Solution();\n        System.out.println(solution.longestWord(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串中的数字之和', 3, 1000, 65536, '题目描述：\n给定一个字符串 s，提取其中所有连续数字并求和。\n\n示例 1：\n输入：a1b23c456\n输出：480\n\n提示：\n- 1+23+456=480。', 'a1b23c456|||480\nabc|||0\n1a2b3|||6', 'class Solution {\n    public int sumNumbers(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.sumNumbers(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL);

INSERT INTO tb_question
(title, difficulty, time_limit, space_limit, content, question_case, default_code, main_fuc, create_by, create_time, update_by, update_time)
VALUES
    ('统计元音字母', 2, 1000, 65536, '题目描述：\n给定一个字符串 s（仅小写字母），统计其中元音字母（a/e/i/o/u）的个数。\n\n示例 1：\n输入：hello\n输出：2\n\n提示：\n- 遍历字符串判断。', 'hello|||2\nabc|||1\nxyz|||0', 'class Solution {\n    public int countVowels(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.countVowels(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('替换字符串中的字符', 1, 1000, 65536, '题目描述：\n给定字符串 s、字符 oldChar、字符 newChar，将 s 中所有 oldChar 替换为 newChar 后输出。\n\n示例 1：\n输入：hello l x\n输出：hexxo\n\n提示：\n- 使用 replace。', 'hello l x|||hexxo\nabc a z|||zbc', 'class Solution {\n    public String replaceChar(String s, char oldChar, char newChar) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        char oldChar = sc.next().charAt(0);\n        char newChar = sc.next().charAt(0);\n        Solution solution = new Solution();\n        System.out.println(solution.replaceChar(s, oldChar, newChar));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串中第一个不重复字符', 3, 1000, 65536, '题目描述：\n给定一个字符串 s（仅小写字母），输出第一个只出现一次的字符。若不存在输出 "none"。\n\n示例 1：\n输入：aabbc\n输出：c\n\n提示：\n- 使用数组计数。', 'aabbc|||c\nabcabc|||none\naabbccd|||d', 'class Solution {\n    public String firstUniqueChar(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.firstUniqueChar(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串中字符出现次数统计', 3, 1000, 65536, '题目描述：\n给定一个字符串 s（仅小写字母），按字母顺序输出每个出现过的字符及其次数，格式如 a2b1c3。\n\n示例 1：\n输入：aabbc\n输出：a2b2c1\n\n提示：\n- 使用计数数组。', 'aabbc|||a2b2c1\nabc|||a1b1c1\naaaa|||a4', 'class Solution {\n    public String charFrequency(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.charFrequency(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串移位', 3, 1000, 65536, '题目描述：\n给定一个字符串 s 和一个整数 k，将字符串循环右移 k 位后输出。\n\n示例 1：\n输入：abcde 2\n输出：deabc\n\n提示：\n- k 可能大于字符串长度，先取模。', 'abcde 2|||deabc\nabc 1|||cab\nabc 3|||abc', 'class Solution {\n    public String rotateRight(String s, int k) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        int k = sc.nextInt();\n        Solution solution = new Solution();\n        System.out.println(solution.rotateRight(s, k));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('字符串比较', 2, 1000, 65536, '题目描述：\n给定两个字符串 a 和 b，若 a 字典序小于 b 输出 -1，等于输出 0，大于输出 1。\n\n示例 1：\n输入：abc abd\n输出：-1\n\n提示：\n- 使用 compareTo。', 'abc abd|||-1\nabc abc|||0\nabd abc|||1', 'class Solution {\n    public int compare(String a, String b) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String a = sc.next();\n        String b = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.compare(a, b));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('十进制转二进制', 2, 1000, 65536, '题目描述：\n给定一个正整数 n，输出它的二进制表示。\n\n示例 1：\n输入：10\n输出：1010\n\n提示：\n- 使用 Integer.toBinaryString()。', '10|||1010\n1|||1\n255|||11111111', 'class Solution {\n    public String toBinary(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution solution = new Solution();\n        System.out.println(solution.toBinary(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('二进制转十进制', 3, 1000, 65536, '题目描述：\n给定一个二进制字符串 s，输出它对应的十进制整数。\n\n示例 1：\n输入：1010\n输出：10\n\n提示：\n- 使用 Integer.parseInt(s, 2)。', '1010|||10\n1|||1\n11111111|||255', 'class Solution {\n    public int toDecimal(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.toDecimal(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('求整数的各位数字', 2, 1000, 65536, '题目描述：\n给定一个正整数 n，将其各位数字从高位到低位输出，以空格分隔。\n\n示例 1：\n输入：123\n输出：1 2 3\n\n提示：\n- 可转为字符串处理。', '123|||1 2 3\n7|||7\n1000|||1 0 0 0', 'class Solution {\n    public int[] digitsArray(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution solution = new Solution();\n        int[] res = solution.digitsArray(n);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('判断 2 的幂', 2, 1000, 65536, '题目描述：\n给定一个正整数 n，判断它是否为 2 的幂。是输出 yes，否则输出 no。\n\n示例 1：\n输入：8\n输出：yes\n\n提示：\n- 使用位运算 n & (n-1) == 0。', '8|||yes\n6|||no\n1|||yes', 'class Solution {\n    public String isPowerOfTwo(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution solution = new Solution();\n        System.out.println(solution.isPowerOfTwo(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('判断回文串（忽略大小写）', 3, 1000, 65536, '题目描述：\n给定一个字符串 s（可能含大小写字母），忽略大小写判断是否为回文串。是输出 yes，否则输出 no。\n\n示例 1：\n输入：Level\n输出：yes\n\n提示：\n- 先转为统一大小写。', 'Level|||yes\nhello|||no\nAa|||yes', 'class Solution {\n    public String isPalindromeIgnoreCase(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.isPalindromeIgnoreCase(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('两数之和（返回下标）', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，第三行输入目标值 target，输出两个下标 i < j 使得 nums[i] + nums[j] == target，以空格分隔。保证有唯一解。\n\n示例 1：\n输入：4\n2 7 11 15\n9\n输出：0 1\n\n提示：\n- 使用 HashMap。', '4\n2 7 11 15\n9|||0 1\n3\n3 2 4\n6|||1 2', 'class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.twoSum(nums, target);\n        System.out.println(res[0] + " " + res[1]);\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('最大子数组和', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，输出连续子数组的最大和。\n\n示例 1：\n输入：5\n-2 1 -3 4 -1\n输出：4\n\n提示：\n- 使用动态规划（Kadane 算法）。', '5\n-2 1 -3 4 -1|||4\n3\n-1 -2 -3|||-1\n3\n1 2 3|||6', 'class Solution {\n    public int maxSubArray(int[] nums) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.maxSubArray(nums));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('买卖股票的最佳时机', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数表示每天股价，只能买卖一次，输出最大利润。\n\n示例 1：\n输入：6\n7 1 5 3 6 4\n输出：5\n\n提示：\n- 记录最小价格并更新利润。', '6\n7 1 5 3 6 4|||5\n3\n7 6 4|||0\n2\n1 2|||1', 'class Solution {\n    public int maxProfit(int[] prices) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] prices = new int[n];\n        for (int i = 0; i < n; i++) prices[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.maxProfit(prices));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('合并两个有序数组', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个升序整数，第三行输入 m，第四行输入 m 个升序整数，输出合并后的升序数组，以空格分隔。\n\n示例 1：\n输入：3\n1 3 5\n3\n2 4 6\n输出：1 2 3 4 5 6\n\n提示：\n- 使用双指针。', '3\n1 3 5\n3\n2 4 6|||1 2 3 4 5 6\n1\n1\n1\n2|||1 2', 'class Solution {\n    public int[] merge(int[] a, int[] b) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n];\n        for (int i = 0; i < n; i++) a[i] = sc.nextInt();\n        int m = sc.nextInt();\n        int[] b = new int[m];\n        for (int i = 0; i < m; i++) b[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.merge(a, b);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('删除有序数组中的重复项', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个升序整数，输出去重后的数组，以空格分隔。\n\n示例 1：\n输入：5\n1 1 2 2 3\n输出：1 2 3\n\n提示：\n- 使用双指针原地去重。', '5\n1 1 2 2 3|||1 2 3\n3\n1 2 3|||1 2 3\n4\n5 5 5 5|||5', 'class Solution {\n    public int[] removeDuplicates(int[] nums) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.removeDuplicates(nums);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('移动零', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，将所有 0 移到数组末尾，保持非零元素顺序不变，输出结果，以空格分隔。\n\n示例 1：\n输入：5\n0 1 0 3 12\n输出：1 3 12 0 0\n\n提示：\n- 双指针。', '5\n0 1 0 3 12|||1 3 12 0 0\n3\n0 0 1|||1 0 0\n4\n1 2 3 4|||1 2 3 4', 'class Solution {\n    public int[] moveZeroes(int[] nums) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.moveZeroes(nums);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('加一', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数表示一个非负整数（高位在前），将该整数加一后输出各位数字，以空格分隔。\n\n示例 1：\n输入：3\n1 2 3\n输出：1 2 4\n\n提示：\n- 处理进位，如 9 9 -> 1 0 0。', '3\n1 2 3|||1 2 4\n1\n9|||1 0\n4\n9 9 9 9|||1 0 0 0 0', 'class Solution {\n    public int[] plusOne(int[] digits) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] digits = new int[n];\n        for (int i = 0; i < n; i++) digits[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.plusOne(digits);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('找出只出现一次的数字', 3, 1000, 65536, '题目描述：\n第一行输入 n（n 为奇数），第二行输入 n 个整数，除一个数字外其余都出现两次，输出只出现一次的数字。\n\n示例 1：\n输入：5\n4 1 2 1 2\n输出：4\n\n提示：\n- 使用异或运算，a^a=0。', '5\n4 1 2 1 2|||4\n1\n7|||7\n3\n1 1 2|||2', 'class Solution {\n    public int singleNumber(int[] nums) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.singleNumber(nums));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL);

INSERT INTO tb_question
(title, difficulty, time_limit, space_limit, content, question_case, default_code, main_fuc, create_by, create_time, update_by, update_time)
VALUES
    ('多数元素', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，找出出现次数超过 n/2 的元素。\n\n示例 1：\n输入：5\n3 2 3 1 3\n输出：3\n\n提示：\n- 可使用摩尔投票法。', '5\n3 2 3 1 3|||3\n3\n1 1 2|||1\n1\n5|||5', 'class Solution {\n    public int majorityElement(int[] nums) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.majorityElement(nums));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('存在重复元素', 2, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数，判断数组中是否存在重复元素。是输出 yes，否则输出 no。\n\n示例 1：\n输入：4\n1 2 3 1\n输出：yes\n\n提示：\n- 使用 HashSet。', '4\n1 2 3 1|||yes\n3\n1 2 3|||no\n1\n5|||no', 'class Solution {\n    public String containsDuplicate(int[] nums) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.containsDuplicate(nums));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('两个数组的交集 II', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数（数组 a），第三行输入 m，第四行输入 m 个整数（数组 b），输出两个数组的交集（含重复），以空格分隔。\n\n示例 1：\n输入：4\n1 2 2 1\n2\n2 2\n输出：2 2\n\n提示：\n- 用 HashMap 计数。', '4\n1 2 2 1\n2\n2 2|||2 2\n3\n4 9 5\n3\n9 4 9|||4 9', 'class Solution {\n    public int[] intersect(int[] a, int[] b) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] a = new int[n];\n        for (int i = 0; i < n; i++) a[i] = sc.nextInt();\n        int m = sc.nextInt();\n        int[] b = new int[m];\n        for (int i = 0; i < m; i++) b[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.intersect(a, b);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('最长公共前缀', 3, 1000, 65536, '题目描述：\n第一行输入 n，接下来 n 行每行一个字符串，输出所有字符串的最长公共前缀。若不存在输出空行。\n\n示例 1：\n输入：3\nflower\nflow\nflight\n输出：fl\n\n提示：\n- 逐列比较。', '3\nflower\nflow\nflight|||fl\n2\nabc\ndef|||\n1\nhello|||hello', 'class Solution {\n    public String longestCommonPrefix(String[] strs) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        String[] strs = new String[n];\n        for (int i = 0; i < n; i++) strs[i] = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.longestCommonPrefix(strs));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('验证回文串（忽略非字母数字）', 3, 1000, 65536, '题目描述：\n给定一个字符串 s，只考虑字母和数字字符，忽略大小写，判断是否为回文串。是输出 yes，否则输出 no。\n\n示例 1：\n输入：A man, a plan, a canal: Panama\n输出：yes\n\n提示：\n- 使用双指针。', 'A man, a plan, a canal: Panama|||yes\nrace a car|||no\n|||yes', 'class Solution {\n    public String isPalindromeValid(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.nextLine();\n        Solution solution = new Solution();\n        System.out.println(solution.isPalindromeValid(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('同构字符串', 3, 1000, 65536, '题目描述：\n给定两个字符串 s 和 t，判断它们是否同构（字符一一对应）。是输出 yes，否则输出 no。\n\n示例 1：\n输入：egg add\n输出：yes\n\n提示：\n- 使用两个 HashMap。', 'egg add|||yes\nfoo bar|||no\npaper title|||yes', 'class Solution {\n    public String isIsomorphic(String s, String t) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        String t = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.isIsomorphic(s, t));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('单词规律', 3, 1000, 65536, '题目描述：\n给定一个模式串 pattern 和一个字符串 str（以空格分隔），判断 str 是否遵循相同规律。是输出 yes，否则输出 no。\n\n示例 1：\n输入：abba dog cat cat dog\n输出：yes\n\n提示：\n- 双向映射。', 'abba dog cat cat dog|||yes\nabba dog cat cat fish|||no\naaaa dog cat cat dog|||no', 'class Solution {\n    public String wordPattern(String pattern, String str) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String pattern = sc.next();\n        String str = sc.nextLine().trim();\n        Solution solution = new Solution();\n        System.out.println(solution.wordPattern(pattern, str));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('快乐数', 3, 1000, 65536, '题目描述：\n给定一个正整数 n，反复将各位数字平方求和，若最终得到 1 则为快乐数（输出 yes），否则进入循环（输出 no）。\n\n示例 1：\n输入：19\n输出：yes\n\n提示：\n- 使用 HashSet 检测循环。', '19|||yes\n2|||no\n1|||yes', 'class Solution {\n    public String isHappy(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.isHappy(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('爬楼梯', 3, 1000, 65536, '题目描述：\n假设你正在爬楼梯，需要 n 阶到达楼顶。每次可以爬 1 或 2 阶，求不同方法数。\n\n示例 1：\n输入：3\n输出：3\n\n提示：\n- 1 ≤ n ≤ 45，用动态规划。', '3|||3\n1|||1\n5|||8', 'class Solution {\n    public int climbStairs(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.climbStairs(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('杨辉三角', 3, 1000, 65536, '题目描述：\n给定行数 n，输出杨辉三角的前 n 行，每行数字以空格分隔，行之间用换行分隔。\n\n示例 1：\n输入：3\n输出：\n1\n1 1\n1 2 1\n\n提示：\n- 每行首尾为 1。', '3|||1\n1 1\n1 2 1\n1|||1', 'class Solution {\n    public List<List<Integer>> generate(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        List<List<Integer>> res = s.generate(n);\n        for (List<Integer> row : res) {\n            for (int i = 0; i < row.size(); i++) {\n                if (i > 0) System.out.print(" ");\n                System.out.print(row.get(i));\n            }\n            System.out.println();\n        }\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('二进制中 1 的个数', 3, 1000, 65536, '题目描述：\n给定一个正整数 n，输出它二进制表示中 1 的个数。\n\n示例 1：\n输入：5\n输出：2\n\n提示：\n- 5 = 101，有 2 个 1。', '5|||2\n1|||1\n255|||8', 'class Solution {\n    public int countOnes(int n) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.countOnes(n));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('丢失的数字', 3, 1000, 65536, '题目描述：\n给定一个包含 0 到 n 中 n 个数的数组，找出缺失的那个数。\n\n示例 1：\n输入：3\n3 0 1\n输出：2\n\n提示：\n- 使用异或或求和公式。', '3\n3 0 1|||2\n2\n0 1|||2\n1\n0|||1', 'class Solution {\n    public int missingNumber(int[] nums) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.missingNumber(nums));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('反转链表（值反转）', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数表示链表节点值，输出反转后的节点值，以空格分隔。\n\n示例 1：\n输入：5\n1 2 3 4 5\n输出：5 4 3 2 1\n\n提示：\n- 使用数组反转或链表反转。', '5\n1 2 3 4 5|||5 4 3 2 1\n3\n1 2 3|||3 2 1', 'class Solution {\n    public int[] reverseList(int[] nums) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.reverseList(nums);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('环形链表判断', 3, 1000, 65536, '题目描述：\n第一行输入 n 和 pos，第二行输入 n 个整数表示链表节点值，pos 表示尾节点连接到的位置（-1 表示无环）。判断是否有环。是输出 yes，否则输出 no。\n\n示例 1：\n输入：4 1\n3 2 0 -4\n输出：yes\n\n提示：\n- 快慢指针法。', '4 1\n3 2 0 -4|||yes\n3 -1\n1 2 3|||no\n1 0\n1|||yes', 'class Solution {\n    public String hasCycle(int[] nums, int pos) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int pos = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.hasCycle(nums, pos));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('相交链表判断', 3, 1000, 65536, '题目描述：\n给定两个数组表示链表节点值，以及相交位置，判断是否相交。相交输出 yes，否则输出 no。\n\n示例 1：\n输入：3 3 2\n1 2 3\n4 5\n输出：yes\n\n提示：\n- 可通过构造链表用双指针。', '3 3 2\n1 2 3\n4 5|||yes\n3 3 -1\n1 2 3\n4 5 6|||no', 'class Solution {\n    public String getIntersection(int[] a, int[] b, int skipA, int skipB) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int m = sc.nextInt();\n        int skipA = sc.nextInt();\n        int[] a = new int[n];\n        for (int i = 0; i < n; i++) a[i] = sc.nextInt();\n        int[] b = new int[m];\n        for (int i = 0; i < m; i++) b[i] = sc.nextInt();\n        Solution s = new Solution();\n        System.out.println(s.getIntersection(a, b, skipA, 0));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('最小栈', 3, 1000, 65536, '题目描述：\n设计一个支持 push、pop、top、getMin 的栈。本题给定一组操作和参数，输出每次查询的结果。\n\n示例 1：\n输入：push -2\npush 0\npush -3\ngetMin\npop\ntop\ngetMin\n输出：-3\n0\n-2\n\n提示：\n- 用辅助栈记录最小值。', 'push -2\npush 0\npush -3\ngetMin\npop\ntop\ngetMin|||-3\n0\n-2', 'class MinStack {\n    public MinStack() {}\n    public void push(int x) {}\n    public void pop() {}\n    public int top() { return 0; }\n    public int getMin() { return 0; }\n}\n\nclass Solution {\n    public int[] run(String[] ops, int[] vals) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        List<String> ops = new ArrayList<>();\n        List<Integer> vals = new ArrayList<>();\n        while (sc.hasNext()) {\n            String op = sc.next();\n            ops.add(op);\n            if (op.equals("push")) vals.add(sc.nextInt());\n            else vals.add(null);\n        }\n        Solution s = new Solution();\n        int[] res = s.run(ops.toArray(new String[0]), vals.stream().mapToInt(v -> v == null ? 0 : v).toArray());\n        for (int r : res) System.out.println(r);\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('队列实现栈', 3, 1000, 65536, '题目描述：\n用两个队列实现一个栈，支持 push、pop、top、empty。给定操作序列，输出每次查询结果。\n\n示例 1：\n输入：push 1\npush 2\ntop\npop\nempty\n输出：2\n2\nno\n\n提示：\n- 保持一个队列为主。', 'push 1\npush 2\ntop\npop\nempty|||2\n2\nno', 'class Solution {\n    public String[] run(String[] ops, int[] vals) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        List<String> ops = new ArrayList<>();\n        List<Integer> vals = new ArrayList<>();\n        while (sc.hasNext()) {\n            String op = sc.next();\n            ops.add(op);\n            if (op.equals("push")) vals.add(sc.nextInt());\n            else vals.add(0);\n        }\n        Solution s = new Solution();\n        String[] res = s.run(ops.toArray(new String[0]), vals.stream().mapToInt(v -> v).toArray());\n        for (String r : res) System.out.println(r);\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('用栈实现队列', 3, 1000, 65536, '题目描述：\n用两个栈实现一个队列，支持 push、pop、peek、empty。给定操作序列，输出每次查询结果。\n\n示例 1：\n输入：push 1\npush 2\npeek\npop\nempty\n输出：1\n1\nno\n\n提示：\n- 入栈到 in，出栈从 out 取。', 'push 1\npush 2\npeek\npop\nempty|||1\n1\nno', 'class Solution {\n    public String[] run(String[] ops, int[] vals) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        List<String> ops = new ArrayList<>();\n        List<Integer> vals = new ArrayList<>();\n        while (sc.hasNext()) {\n            String op = sc.next();\n            ops.add(op);\n            if (op.equals("push")) vals.add(sc.nextInt());\n            else vals.add(0);\n        }\n        Solution s = new Solution();\n        String[] res = s.run(ops.toArray(new String[0]), vals.stream().mapToInt(v -> v).toArray());\n        for (String r : res) System.out.println(r);\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('有效的括号', 3, 1000, 65536, '题目描述：\n给定一个只包含 ()[]{} 的字符串 s，判断括号是否有效匹配。有效输出 yes，否则输出 no。\n\n示例 1：\n输入：()[]{}\n输出：yes\n\n提示：\n- 使用栈。', '()[]{}|||yes\n(]|||no\n([)]|||no', 'class Solution {\n    public String isValid(String s) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution solution = new Solution();\n        System.out.println(solution.isValid(s));\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL),
    ('每日温度', 3, 1000, 65536, '题目描述：\n第一行输入 n，第二行输入 n 个整数表示每天温度，输出每天需要等待多少天才能遇到更高温度，无则输出 0，以空格分隔。\n\n示例 1：\n输入：8\n73 74 75 71 69 72 76 73\n输出：1 1 4 2 1 1 0 0\n\n提示：\n- 单调栈。', '8\n73 74 75 71 69 72 76 73|||1 1 4 2 1 1 0 0\n3\n30 40 50|||1 1 0\n3\n50 40 30|||0 0 0', 'class Solution {\n    public int[] dailyTemperatures(int[] t) {\n        // TODO: 在这里编写你的代码\n    }\n}', 'import java.util.*;\nimport java.io.*;\nimport java.math.*;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        int[] t = new int[n];\n        for (int i = 0; i < n; i++) t[i] = sc.nextInt();\n        Solution s = new Solution();\n        int[] res = s.dailyTemperatures(t);\n        for (int i = 0; i < res.length; i++) {\n            if (i > 0) System.out.print(" ");\n            System.out.print(res[i]);\n        }\n        System.out.println();\n    }\n}\n{{USER_CODE}}', 1, '2026-10-09 08:49:24', NULL, NULL);